### ISSUE TITLE
Relationship Direction can't be retained after using call apoc.refactor.cloneNodesWithRelationships

### ISSUE THREAD

**Issue by wanzzzone** [neo4j-contrib/neo4j-apoc-procedures#936] opened 2018-10-02 10:56 UTC
Hi, 

I'm using neo4j community edition 3.0.6 and apoc 3.0.8.6.
I'm having this issues where i tried to copy a node that already have multiple relationship.
Then when I use call apoc.refactor.cloneNodesWithRelationships([node1,node2,…​]) the nodes and its relationship are copied. 
But the relationship direction is wrong. 
Attached the image below. As You can see in the image the relationship direction between A-B is wrong. Like it seems all the relationship created there is considered as outgoing relationship.
Is this a bug on apoc 3.0.8.6 or is there any solution regarding this issue ?

Thank you
![error relationship direction](https://user-images.githubusercontent.com/18481779/46344747-7d8d9b00-c66c-11e8-8f81-c7832d9eec6e.png)

**Comment by wanzzzone** [comment] 2018-10-03 04:31
> This may be a duplicate of #229.

> `apoc.refactor. GraphRefactoring.doCloneNodes()` does the wrong thing when its `withRelationships` argument is true. It should not be calling `copyRelationships(node, copy, false)` for each node/copy pair -- as if no other nodes are going to be copied. That will cause some of the endpoints of the newly created relationships to end up attached to an original node instead of a copy.

Hi, I just saw the issue that You referenced. It seems the problem is different. My problem is the direction is wrong. Meanwhile the issue #229 problem is the relationship not copied correctly.

**Comment by cybersam** [comment] 2018-10-04 04:36
There are new relationships going in the wrong direction in both issues. There is a very strong possibility they are caused by the same issue.

**Comment by wanzzzone** [comment] 2018-10-04 04:59
Hmm so currently its still not fixed yet ? Or is there any other solution ?
Right now I'm inverting the wrongly created relationship direction manually.

**Comment by conker84** [comment] 2018-10-07 09:52
Hi @wanzzzone you are using an old version of Neo4j the bug is fixed in 3.4
We have no plans to support APOCs in 3.0.x please consider upgrading to the last Neo version.
Thanks for your feedback.

**Closed** 2018-10-07 10:11 UTC
Labels: Larus
