### ISSUE TITLE
apoc.periodic.iterate NullPointerException

### ISSUE THREAD

**Issue by mneedham** [neo4j-contrib/neo4j-apoc-procedures#759] opened 2018-03-12 08:53 UTC
If I run the algorithm in parallel I sometimes get this exception:

```
call apoc.periodic.iterate('match (n) return n',
'detach delete n',   {batchSize:1000, parallel: true })
```

```
╒═════════╤═══════╤═══════════╤═════════════════════╤══════════════════╤═══════════════╤═════════╤═══════════════╤══════════════════════════════════════════════════════════════════════╤═════════════════════════════════════════════════════════╤═══════════════╕
│"batches"│"total"│"timeTaken"│"committedOperations"│"failedOperations"│"failedBatches"│"retries"│"errorMessages"│"batch"                                                               │"operations"                                             │"wasTerminated"│
╞═════════╪═══════╪═══════════╪═════════════════════╪══════════════════╪═══════════════╪═════════╪═══════════════╪══════════════════════════════════════════════════════════════════════╪═════════════════════════════════════════════════════════╪═══════════════╡
│3        │2672   │0          │1000                 │2000              │2              │0        │{}             │{"total":3,"committed":1,"failed":2,"errors":{"java.lang.NullPointerEx│{"total":2672,"committed":1000,"failed":2000,"errors":{}}│false          │
│         │       │           │                     │                  │               │         │               │ception":2}}                                                          │                                                         │               │
└─────────┴───────┴───────────┴─────────────────────┴──────────────────┴───────────────┴─────────┴───────────────┴──────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────┴───────────────┘
```

**Comment by InverseFalcon** [comment] 2018-03-12 21:44
`parallel:true` isn't a good fit for this. Some nodes will have relationships between them, and running with `parallel:true` has the potential to introduce race conditions. 

Thread 1 begins detaching Node A's, relationships, and locks on rel `ab` between `A` and `B`.
Thread 2 begins detaching Node B's relationships, and waits to lock on rel `ab` between `A` and `B`.

Thread 1 finishes deletion of `ab` (and possibly deletes node `A`
Thread 2 attempts to acquire locks on `A`, `B`, and `ab`, but `ab` (and possibly `A`) are already deleted.

This said, it would be worth checking with the Cypher team to see if we can guard against NPEs here and figure out what the expected behavior should be...silent fail?

**Comment by jexp** [comment] 2018-03-27 01:19
We could use the `retries` option for this one, but I have to implement proper back-off for retries.

**Comment by pradeepponduri** [comment] 2018-07-29 00:35
How can we increase number of threads?

**Comment by bsquire0128** [comment] 2018-12-18 19:09
Has this been solved? I am finding a similar error most likely due to race conditions. Should we just use iterate with parallel:false or commit instead for batch deleteing?

**Comment by jexp** [comment] 2018-12-18 23:46
You can use parallel:false

I guess it's related to relationships that have been deleted from one node being deleted from the other too.
Due to `detach delete`.

So what you said should work:

1. delete relationships first in parallel
2. And then the nodes.

**Comment by conker84** [comment] 2021-05-13 09:54
Closing this as we have a valid answer

**Closed by conker84** 2021-05-13 09:54 UTC
