### ISSUE TITLE
Unable to Delete nodes and relationships with apoc.trigger.propertiesByKey($removedNodeProperties, "nodeProperty")

### ISSUE THREAD

**Issue by srnnukala** [neo4j-contrib/neo4j-apoc-procedures#3216] opened 2022-10-12 04:07 UTC
Expected Behavior (Mandatory)
Delete nodes and relationships while having  apoc.trigger.propertiesByKey($removedNodeProperties,"progenitorId")

Sample apoc trigger in production : 
  1)  CALL apoc.trigger.add('requiredIdentifiers_removedNodeProperties_preventRemovalOnProgenitorId',
       'UNWIND apoc.trigger.propertiesByKey($removedNodeProperties,"progenitorId") AS prop WITH prop.node AS n, prop.old 
        AS oldValue SET n.progenitorId=oldValue RETURN 0', {phase:'before'});
  2) CALL apoc.trigger.add('requiredIdentifiers_removedRelationshipProperties_preventRemovalOnExternalId',
       'UNWIND apoc.trigger.propertiesByKey($removedRelationshipProperties,"externalId") AS prop WITH prop.relationship AS r, 
       prop.old AS oldValue SET r.externalId=oldValue RETURN 0', {phase:'before'});

Actual Behavior (Mandatory)
Neo.ClientError.Transaction.TransactionHookFailed: Error executing trigger requiredIdentifiers_removedNodeProperties_preventRemovalOnProgenitorId in phase before
org.neo4j.graphdb.TransactionFailureException: Unable to complete transaction.

How to Reproduce the Problem
-> CREATE DATABASE dummy
-> CALL apoc.trigger.add('requiredIdentifiers_removedNodeProperties_preventRemovalOnProgenitorId',
'UNWIND apoc.trigger.propertiesByKey($removedNodeProperties,"progenitorId") AS prop WITH prop.node AS n, prop.old AS oldValue
SET n.progenitorId=oldValue RETURN 0',
{phase:'before'});
-> CREATE (node:dummyActivity {progenitorId : 123456})
-> MATCH (n:Activity) where n.progenitorId = 123456 delete n

Background 
Earlier we were using neo4j 3.5.18 and apoc 3.5.0.12-all. 
With apoc.triggers in place, we don't allow users to delete/update the node properties or relationship properties, however we give them right and were able to delete nodes and relationship. 

Simple Dataset (where it's possibile)
Any dataset.

Steps (Mandatory)
Adding the apoc trigger

Versions
OS: Linux
Neo4j: 4.4.8
Neo4j-Apoc: 4.4.0.4
(have also tried Apoc 4.3.0.5
[apoc_trigger_error.pdf](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/9761423/apoc_trigger_error.pdf)
 with same result)

**Comment by vga91** [comment] 2022-10-12 10:18
@srnnukala 
Maybe I'm missing something but I don't understand why you wrote the `SET n.progenitorId = oldValue`. 
That is, it seems that you are trying to do a `SET` on a node that needs to be deleted.

In any case, apart from the internal id it is not possible to obtain node/relationships information of a node that needs to be deleted (in this case the `progenitorId` property) , hence the error.

To get this information and use it with other nodes / relations you could use the `apoc.trigger.toNode` and` apoc.trigger.toRelatioship`,  [see here, in section `Handle deleted entities`](https://neo4j.com/labs/apoc/4.4/background-operations/triggers/ ).

Just as an example, in the below case I set the "progenitorId" property in a property `prop1` on a node `(:Report)`:
```
CALL apoc.trigger.add('example', "UNWIND $deletedNodes as deletedNode 
WITH apoc.trigger.toNode(deletedNode, $removedLabels, $removedNodeProperties) AS deletedNode 
MATCH (r:Report) WITH r, deletedNode
SET r.prop1=apoc.any.property(deletedNode,'progenitorId')" , 
{phase: 'before'})
```

**Comment by srnnukala** [comment] 2022-10-14 14:44
@vga91 
The whole idea is to not allow the required properties on node or relationship to be deleted, but we should be able to delete the entire  node or relationship. 
#[**In any case, apart from the internal id it is not possible to obtain node/relationships information of a node that needs to be deleted (in this case the progenitorId property) , hence the error.**] : We are able to obtain a node/ relationship based on the 'progenitorId'.
But what I am not able to figure out is, the trigger should be activated only when properties are removed (which is happening when using neo4j 3.5.18 and apoc 3.5.0.12) and should be silent when the entire node/relationship is deleted.

**Comment by vga91** [comment] 2022-10-24 13:38
@srnnukala Ok, now I got it. 
In neo4j 4, when I delete a node, the transaction also considers the property nodes as deleted (same thing for relationships).
This is a wanted behavior, intrinsic in neo4j, [see here](https://github.com/neo4j/neo4j/blob/4.4/community/graphdb-api/src/main/java/org/neo4j/graphdb/event/TransactionData.java#L88).

Therefore, you could use a workaround like this, instead of your 1st trigger:
```
CALL apoc.trigger.add('requiredIdentifiers_removedNodeProperties_preventRemovalOnProgenitorId,
"UNWIND apoc.trigger.propertiesByKey($removedNodeProperties, 'progenitorId') AS prop 
WITH id(prop.node) AS idNode, prop.old as oldValue
match (node) where id(node) = idNode set node.progenitorId = oldValue 
RETURN null", {phase:'before'});
```
where I look for a node with an id equal to the one extrapolated from `$removedNodeProperties` and, if it exists, I set the property just deleted.

Similarly, the second trigger could become:
```
CALL apoc.trigger.add('requiredIdentifiers_removedRelationshipProperties_preventRemovalOnExternalId,
'UNWIND apoc.trigger.propertiesByKey($removedRelationshipProperties,"externalId") AS prop 
WITH id(prop.relationship) AS idRel, prop.old AS oldValue 
match ()-[rel]->() where id(rel) = idRel set rel.externalId = oldValue 
RETURN null', {phase:'before'});
```

**Comment by vga91** [comment] 2023-01-24 10:36
@srnnukala 
Closing this as a possible workaround has been posted.
Feel free to reopen in case the problem is still present or you have more info to share

**Closed by vga91** 2023-01-24 10:36 UTC
Labels: core-functionality
