### ISSUE TITLE
Function apoc.refactor.mergeNodes() doesn't merge relationship properties

### ISSUE THREAD

**Issue by ThachNgocTran** [neo4j-contrib/neo4j-apoc-procedures#1665] opened 2020-09-11 20:49 UTC
## Expected Behavior (Mandatory)

Following the guide [Merge Nodes](https://neo4j.com/labs/apoc/4.1/graph-updates/graph-refactoring/merge-nodes/):

> Relationships properties are managed with the same nodes' method, if properties parameter isn’t set relationships properties are combined.

## Actual Behavior (Mandatory)

Relationship properties aren't merged, even if it is specifically indicated.

### Steps (Mandatory)

Simple graph:

```
CREATE (a:User {name: "A", communityId: 2}), (b:User {name: "B", communityId: 2}), (c:User {name: "C", communityId: 2}), (x:User {name: "X", communityId: 1}), (y:User {name: "Y", communityId: 1}), (z:User {name: "Z", communityId: 1}), (w:User {name: "W", communityId: 1}), (a)-[:LINK {weight: 1}]->(b), (b)-[:LINK {weight: 1}]->(c), (c)-[:LINK {weight: 1}]->(a), (b)-[:LINK {weight: 1}]->(z), (z)-[:LINK {weight: 1}]->(x), (z)-[:LINK {weight: 1}]->(w), (w)-[:LINK {weight: 1}]->(y), (y)-[:LINK {weight: 1}]->(x), (b)-[:LINK {weight: 1}]->(w)
```

It will look like this: (all `LINK`s have weight of 1)

![a](https://user-images.githubusercontent.com/9520123/92972025-cfa6e000-f481-11ea-9233-4b746c5b41d6.png)

The Cypher query:

```
MATCH (n:User)
WITH n.communityId AS communityId, COLLECT(n) AS nodes
CALL apoc.refactor.mergeNodes(nodes, {
    properties: {
        name: 'combine',
        communityId: 'discard',
        weight: 'combine'
    },
    mergeRels: true
})
YIELD node
RETURN node
```

The result graph:

![b](https://user-images.githubusercontent.com/9520123/92972090-ebaa8180-f481-11ea-89e6-90adfb1910a6.png)

The `weight` property of `LINK` relationship doesn't change! It should be `[1,1]` or maybe `2` (1 + 1 = 2).

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: Windows 8.1 x64
  - Neo4j: Neo4j Desktop 1.3.4 (Engine: 4.1.1) (Settings: default)
  - Neo4j-Apoc: v4.1.0.2
  - Graph Data Science Library: **not installed**

**Comment by conker84** [comment] 2020-10-01 09:07
@ThachNgocTran thanks a lot for reporting this. The issue is the same as #1572 and the PR #1605 will fix it, so I'm closing this issue. Feel free to reopen it in case you'll find the bug again in future APOC release!

**Closed by conker84** 2020-10-01 09:07 UTC
