### ISSUE TITLE
jquery not returning good result on apoc.load.html

### ISSUE THREAD

**Issue by thebruuu** [neo4j-contrib/neo4j-apoc-procedures#1392] opened 2020-01-30 12:54 UTC
Hi

Given the html file below:
```
<html>
<body>
<h2 id='KPILIST'> Blah Blah 1</h2>
<div>
	<div>
		<table>
			<tbody>
				<tr><th>Col 1 Header</th><th>Col 2 Header</th></tr>
				<tr><td>Line 1.1 Value</td><td>Line 2.1 Header</td></tr>
				<tr><td>Line 2.1 Value</td><td>Line 2.2 Value</td></tr>
			</tbody>
		</table>
	</div>
</div>
<div>
	<div>
		<table>
			<tbody>
				<tr><th>Col 1 Header T2</th><th>Col 2 Header T2</th></tr>
				<tr><td>Line 1.1 Value T2</td><td>Line 2.1 Header T2</td></tr>
				<tr><td>Line 2.1 Value T2</td><td>Line 2.2 Value T2</td></tr>
				</tbody>
		</table>
	</div>
</div>

</body>
</html>
```
I would expect the below code to return the first bloc of 3 lines from the first table above
```

CALL apoc.load.html("file:///XXX.html",{line: "#KPILIST ~ div:eq(0) div > table tr"}) yield value as lineList
unwind (lineList.line) as L
RETURN L
```
But unfortunately nothing is returned

**Comment by sarmbruster** [comment] 2020-01-30 14:27
responded in https://community.neo4j.com/t/jquery-not-returning-expected-result-on-apoc-load-html/14188/2
Not a bug, so closing this one.

**Closed by sarmbruster** 2020-01-30 14:27 UTC
Labels: invalid

**Comment by thebruuu** [comment] 2020-01-31 09:39
Yepp I cam back to delete it but you were faster.
Sorry for disturb
