### ISSUE TITLE
apoc.index with auto update does not update on delete

### ISSUE THREAD

**Issue by h-oll** [neo4j-contrib/neo4j-apoc-procedures#746] opened 2018-02-27 10:02 UTC
When using a manual index with autoupdate = true, nodes get added to the index correctly, but fail to be removed when nodes are deleted in a subsequent query.

**Comment by sarmbruster** [comment] 2018-02-28 17:53
which version of neo4j are you using?

**Comment by h-oll** [comment] 2018-02-28 18:07
Hi, I use 3.3

**Comment by sarmbruster** [comment] 2018-03-01 09:50
the root cause for this is a regression in neo4j 3.3.3. There's a pending PR fixing this - should be part of next neo4j release. Since we won't fix it in apoc, I'll close this ticket.

**Comment by sarmbruster** [comment] 2018-03-01 09:50
for reference: https://github.com/neo4j/neo4j/pull/11133

**Closed by sarmbruster** 2018-03-01 09:50 UTC

**Comment by h-oll** [comment] 2018-03-02 09:52
@sarmbruster : great news. Thanks for your help. 

Meanwhile I've found a way to resort to natives indexes for doing the job. And I might keep this workaround as it's pretty efficient.
