### ISSUE TITLE
java.lang.NullPointerException when setting the type of a property to "datetime" in the mapping config of apoc.load.csv()

### ISSUE THREAD

**Issue by srpalko** [neo4j-contrib/neo4j-apoc-procedures#3218] opened 2022-10-13 01:13 UTC
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)
I'm using apoc.periodic.iterate with apoc.load.csv to process CSV files. In the configuration map of apoc.periodic.iterate, I'm using the mapping key to set the types of the fields. When give a value of "datetime" I expect the field to be parsed into a datetime property. 

## Actual Behavior (Mandatory)
When I set mapping; { date_prop: {type: "datetime"} }, the query fails to invoke apoc.periodic.iterate caused by java.lang.NullPointerException. If I change the type to "string' it works fine.

### Simple Dataset (where it's possible)

```
":LABEL","log_id","access_date","log_type","full_text_access","cid","source_system","external_source","name","id"
"Session","232387464","2022-05-01T00:00:30","library_login","","0","","","session","log-232387449"
"Session","232387449","2022-05-01T00:00:06","Meta_Data_View","False","1000030957","PROD","","session","log-232387454"

```

```
        CALL apoc.load.directory("access-subgraph-*-vertices-*.csv") YIELD value 
        WITH value as url
        CALL apoc.periodic.iterate(
            'CALL apoc.load.csv(
                $url,
                {
                    header: true,
                    ignore: [":LABEL"],
                    nullValues: [""],
                    mapping: {
                        name: {type: "string"},
			log_id: {type: "string"},
			access_date: {type: "datetime"},
			log_type: {type: "string"},
			full_text_access: {type: "string"},
			cid: {type: "string"},
			source_system: {type: "string"},
			external_source: {type: "string"}
                    }
                }
            ) YIELD map AS row RETURN row',
            'MERGE (node:Session {id: row.id}) 
             ON CREATE SET node = row
             ON MATCH SET node = row',
            {batchSize: 10000, parallel: true, params: {url: url}}
        ) YIELD batches, total 
          RETURN datetime() AS timestamp, 'access-subgraph-*' AS file_type, batches, total;
```

### Steps (Mandatory)

  1. Place CSV file in the import directory
  2. Call the above query
  

## Specifications (Mandatory)
32 GB RAM, Intel Xeon Platinum 8259CL @ 2.50GHz

Currently used versions

### Versions

  - OS: Ubuntu 18.04.6 LTS
  - Neo4j: 4.4.12
  - Neo4j-Apoc: 4.4.0.9

**Comment by vga91** [comment] 2024-01-16 11:01
The issue should be caused by APOC Core code, so it cannot be resolved in this repository.

I created a task on Core to fix the problem.

In the meantime, as a workaround, can you try changing `{type: "datetime"}` to ``{type: "datetime", optionalData: {}}``?

**Closed** 2024-03-19 10:20 UTC
Labels: extended-functionality
