### ISSUE TITLE
APOC BUG ？

### ISSUE THREAD

**Issue by 444728248** [neo4j-contrib/neo4j-apoc-procedures#781] opened 2018-04-05 02:03 UTC
This is the latest neo4j version is 3.3.4  and apoc  is apoc-3.3.0.2-all.jar

# Neo.ClientError.Procedure.ProcedureCallFailed
Failed to invoke procedure `apoc.path.subgraphAll`: Caused by: java.lang.NoClassDefFoundError: org/apache/commons/collections/IteratorUtils

CQL: 
MATCH (user:People) WHERE user.name = '蔡成功'
CALL apoc.path.subgraphAll(user, {relationshipFilter:"RATED"}) YIELD nodes, relationships
RETURN nodes, relationships;

The problem has not been solved yet?
https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases

**Comment by sarmbruster** [comment] 2018-04-08 09:06
Duplicate of #765 - already fixed but not yet released.

**Closed by sarmbruster** 2018-04-08 09:06 UTC
