### ISSUE TITLE
Failed to invoke procedure `apoc.export.graphml.all`: Caused by: java.lang.RuntimeException: Import from files not enabled, please set apoc.import.file.enabled=true in your neo4j.conf”

### ISSUE THREAD

**Issue by waelmcse** [neo4j-contrib/neo4j-apoc-procedures#546] opened 2017-08-15 18:51 UTC
I am trying to export my neo4j 3.2.3 database to graphml
I have placed apoc jar file 3.2.0.4 in plugins folder
using call apoc.export.graphml.all(“out.graphml”,{})
I get Error “Failed to invoke procedure `apoc.export.graphml.all`: Caused by: java.lang.RuntimeException: Import from files not enabled, please set apoc.import.file.enabled=true in your neo4j.conf”
I already did modified neo4j.conf and add apoc.import.file.enabled=true
Still having same Error

**Comment by kullervo16** [comment] 2018-02-05 10:01
Same issue with neo4j 3.2.3 and apoc 3.2.3.5... so not related to a particular version.

The solution is given on stackoverflow : https://stackoverflow.com/questions/41764539/neo4j-3-1-0-apoc-export-graphml-issue

Especially the hint about really stopping the process is very interesting. Maybe this information should be added to the hint to avoid people running into this again...

**Comment by conker84** [comment] 2019-04-02 14:31
closed as is a duplicate of #775
feel free to reopen if it surface again

**Closed by conker84** 2019-04-02 14:31 UTC
Labels: Larus
