### ISSUE TITLE
Initializing secondary database in apoc initializers results in cryptic "Unsupported component state for 'multi-database'" error

### ISSUE THREAD

**Issue by jameswylyreasint** [neo4j-contrib/neo4j-apoc-procedures#1947] opened 2021-06-01 20:43 UTC
## Expected Behavior (Mandatory)
Upon initialization of the system database, a second database should be created via the direct commands on the system db.

## Actual Behavior (Mandatory)
An exception is thrown and execution is terminated. "Unsupported component state for 'multi-database': The sub-graph is unsupported because it is too old, this component cannot function" (This is similar in structure to the `UNSUPPORTED` status codes from dbms.upgradeStatus)

Full stack trace:
```
 2021-06-01 20:38:24.188+0000 ERROR Failed to start Neo4j on dbms.connector.http.listen_address, a socket address. If missing port or hostname it is acquired from dbms.default_listen_address. Error starting Neo4j database server at /data/databases
 java.lang.RuntimeException: Error starting Neo4j database server at /data/databases
 	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:198)
 	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:158)
 	at com.neo4j.server.enterprise.EnterpriseManagementServiceFactory.createManagementService(EnterpriseManagementServiceFactory.java:38)
 	at com.neo4j.server.enterprise.EnterpriseBootstrapper.createNeo(EnterpriseBootstrapper.java:20)
 	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:117)
 	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:87)
 	at com.neo4j.server.enterprise.EnterpriseEntryPoint.main(EnterpriseEntryPoint.java:25)
 Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.dbms.database.DefaultSystemGraphInitializer@bbd4791' was successfully initialized, but failed to start. Please see the attached cause exception "Unsupported component state for 'multi-database': The sub-graph is unsupported because it is too old, this component cannot function".
 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:463)
 	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:110)
 	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:189)
 	... 6 more
 Caused by: java.lang.IllegalStateException: Failed to initialize system graph component 'multi-database': Unsupported component state for 'multi-database': The sub-graph is unsupported because it is too old, this component cannot function
 	at org.neo4j.dbms.database.SystemGraphComponents.initializeSystemGraph(SystemGraphComponents.java:93)
 	at org.neo4j.dbms.database.DefaultSystemGraphInitializer.initializeSystemGraph(DefaultSystemGraphInitializer.java:41)
 	at org.neo4j.dbms.database.SystemGraphInitializer.start(SystemGraphInitializer.java:29)
 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:442)
 	... 8 more
 Caused by: java.lang.IllegalStateException: Unsupported component state for 'multi-database': The sub-graph is unsupported because it is too old, this component cannot function
 	at org.neo4j.dbms.database.AbstractSystemGraphComponent.initializeSystemGraph(AbstractSystemGraphComponent.java:130)
 	at org.neo4j.dbms.database.SystemGraphComponents.lambda$initializeSystemGraph$2(SystemGraphComponents.java:85)
 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
 	at org.neo4j.dbms.database.SystemGraphComponents.initializeSystemGraph(SystemGraphComponents.java:85)
 	... 11 more
```

## How to Reproduce the Problem
Using apoc initializers for database initialization, include this line to ask the system to create a second database in the instance

```` 
apoc.initializer.system=CREATE DATABASE mydb
````

### Steps (Mandatory)

  1. Include apoc initializers as described above and start the database

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: macOS 10.15.7
  - Neo4j: 4.1.3-enterprise
  - Neo4j-Apoc: 4.1.0.4

**Comment by jameswylyreasint** [comment] 2021-06-01 22:17
From digging further into some source the issue seems to be coming from [here](https://github.com/neo4j/neo4j/blob/4.1/community/neo4j/src/main/java/org/neo4j/dbms/database/DefaultSystemGraphComponent.java#L64)  where a query is being made to the system database for some default nodes.... and somehow these nodes are not in place  when using this initializer command.

**Comment by ivangreene** [comment] 2021-06-01 22:34
I have debugged this and found that this is ultimately due to the status being UNSUPPORTED here: https://github.com/neo4j/neo4j/blob/4.1/community/neo4j/src/main/java/org/neo4j/dbms/database/DefaultSystemGraphComponent.java#L64
The check of hasDatabaseNode (any node with label Database exists) is true, but the check of hasSystemDatabaseNode (node with label Database and 'name' of 'system' exists) is false, so status is UNSUPPORTED instead of UNINITIALIZED. This means that we don't go through the UNINITIALIZED flow here to create the `:Database(name='system')` node among other setup: https://github.com/neo4j/neo4j/blob/4.1/community/kernel/src/main/java/org/neo4j/dbms/database/AbstractSystemGraphComponent.java#L84 ,
but just fail with the error here: https://github.com/neo4j/neo4j/blob/4.1/community/kernel/src/main/java/org/neo4j/dbms/database/AbstractSystemGraphComponent.java#L129-L130

**Comment by jexp** [comment] 2023-01-19 13:01
@vga91 is this something we fixed with the lifeccycle/multidb updates a while ago?

**Comment by vga91** [comment] 2024-01-11 13:35
@jameswylyreasint 

The problem is no longer present on the latest 4.x and 5.x versions, i.e. 4.4.0.23 and 5.15.
I'm closing the issue, even considering that version 4.1 is no longer supported.

Feel free to reopen the issue in case you still have problems

**Closed by vga91** 2024-01-11 13:35 UTC
Labels: core-functionality
