### ISSUE TITLE
apoc.index.search fails if some of the indexed nodes are deleted

### ISSUE THREAD

**Issue by arsanjea** [neo4j-contrib/neo4j-apoc-procedures#697] opened 2017-12-11 16:33 UTC
The ```apoc.index.search``` procedure will fail if some of the indexed nodes are deleted

## Expected Behavior
Apoc.index.search searches for all matching nodes, ignoring deleted indexed nodes.

## Current Behavior
apox.index.search will fail with the current error: 

## Possible Solution
```Failed to invoke procedure `apoc.index.search`: Caused by: org.neo4j.graphdb.NotFoundException: Node 79 not found``` (79 being the ID() of a deleted indexed node

**Comment by vstruchkov** [comment] 2017-12-16 21:39
I have this bug too
https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/700

**Comment by arsanjea** [comment] 2018-04-08 06:32
Hey guys, anyone willing to look at this or help?

**Comment by sarmbruster** [comment] 2018-04-08 09:10
fixed in https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/030dbf50be73091ed421d0f05ad591cc48a8fdb5 not yet released. Duplicate of #700

**Closed by sarmbruster** 2018-04-08 09:10 UTC
