### ISSUE TITLE
Trigger is null / empty after upgrade to 3.4.0

### ISSUE THREAD

**Issue by razbar** [neo4j-contrib/neo4j-apoc-procedures#848] opened 2018-07-09 09:03 UTC
Neo4j version: 3.4.0
APOC version: 3.4.0.1

Operating system: AWS Linux

Steps to reproduce: Upgrade DB version from 3.2.9 -> 3.4.0

Expected behaviour:  triggers should work as it was

Actual behaviour: After the upgrade the trigger query is null

**Comment by alexiudice** [comment] 2018-07-14 20:22
Hey razbar!  I was wondering when you said ‘Upgrade DB version from 3.2.9 -> 3.4.0` do you mean your Neo4j version or your apoc version?  I assume you meant Neo4j, but I just wanted to check.

**Comment by NivTikolski** [comment] 2018-07-15 06:43
@alexiudice 
we upgrade neo4j from 3.2.9 to 3.4.0/1
when we ran the query apoc.trigger.list  we get our trigger but the trigger's query is null.
apoc.trigger.enabled is of course true.
for now we removed the trigger and add it again, but it is important bug you need to solve.

**Comment by alexiudice** [comment] 2018-07-16 22:40
@NivTikolski it an important problem _we_ need to solve :).

And I understand what you mean now by “the trigger query is null”. 

When you updated your neo4j version did you also update your apoc version? Just asking since I’m not sure an apoc version 3.4.0.1 would work with neo4j 3.2.9 and wanted to know what apoc version you were using for neo4j 3.2.9. 

I have a few ideas about what may be causing the null query. If you fork the neo4j-apoc-procedures and checkout branches 3.2 and 3.4 you can follow along with my observations in the ‘Trigger.java’ file:

I know that apoc version 3.4+ uses the string ‘kernalTransaction’ to identify the trigger query string, while previous versions use the identifier ‘statement’. I’m wondering if the change in how the query string is identified would cause the trigger query to be null. If the other parts of the trigger, like ‘name’ and ‘selector’ were not null I have a good feeling this is the cause of the null trigger query. 

Similarly I see that the TriggerHandler constructor changed between apoc 3.2 and 3.4. In apoc version 3.4+ the TriggerHandler uses EmbeddedProxySPI.class while previous versions uses NodeManager.class to resolve dependencies and load the triggers that have been persisted. 

So I have a feeling its one of those two changes. 

I am wondering were other parts of the trigger, like “name” or “selector” also null? Or did that happen just to “query”?

Also, when you upgraded from neo 3.2.9 to 3.4.0 how did you do your data migration? Did you directly copy and paste your db files,  use the neo4j console to export and import, or do something else?  If you let me know I can try to reproduce the error.

**Comment by NivTikolski** [comment] 2018-07-17 11:35
@alexiudice 
hi,
as raz said, apoc version 3.4.0.1
only the query was null.
for how i upgraded the data? i copy the data, add the upgrade=true in the config.

**Comment by NivTikolski** [comment] 2018-07-25 08:08
@alexiudice 
any news?

**Comment by alexiudice** [comment] 2018-07-25 13:57
@NivTikolski I've made a commit that I think will fix the problem. 

Because I cannot reproduce the problem if you could try building an apoc jar with the changes from that commit and then retry upgrading to see if it works. The triggers 'query' field should not be null.

**Comment by jexp** [comment] 2018-07-25 16:09
I think it might be a neo4j upgrade issue not an apoc issue

**Comment by conker84** [comment] 2021-05-13 10:55
Fixed in newer versions

**Closed by conker84** 2021-05-13 10:55 UTC
