### ISSUE TITLE
Performance degradation due to custom function

### ISSUE THREAD

**Issue by davidkgp** [neo4j-contrib/neo4j-apoc-procedures#2404] opened 2021-12-21 18:20 UTC
## Guidelines

When I use custom function in where clause the performance of my query degrades in terms of query duration. refer screenshot

## Expected Behavior (Mandatory)

Performance should be same or better :)

## Actual Behavior (Mandatory)

Performance degrades

### Simple Dataset (where it's possibile)

I used the movie graph of neo4j and added property age to all the persons with numerical value.
I assigned all the actors name starting with Tom age> 40.

```
MATCH (n:Person)
SET n.age = 35

MATCH (n:Person)
where n.name starts with "Tom"
SET n.age = 45

```

### Steps (Mandatory)

```
//query without custom function
profile match (n:Person) where EXISTS(n.age) AND n.age >40 return n.name 

//added a custom function
CALL apoc.custom.declareFunction('IsOverForty(node::NODE) ::BOOLEAN',
'RETURN (EXISTS($node.age) AND $node.age > 40)');

//query with custom function
profile match (n:Person) where custom.IsOverForty(n) return n.name

```

## Screenshots (where it's possibile)

![image](https://user-images.githubusercontent.com/34774712/146979110-cf4bd977-7797-47a8-aea2-51a54ae5b4ce.png)

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: Docker
  - Neo4j:4.2.10
  - Neo4j-Apoc:4.2.0.9

**Comment by vga91** [comment] 2023-11-21 14:04
In this particular case, the performances are lower because, every time we execute the `IsOverForty()` function, a `Transaction.execute("RETURN (EXISTS($node.age) AND $node.age > 40", <nodeParams>)` (https://github.com/neo4j/neo4j/blob/5.13/community/graphdb-api/src/main/java/org/neo4j/graphdb/Transaction.java#L167) 

is executed under the table, which is then done for each node.

By creating a `CALL apoc.custom.declareFunction('over40() :: ANY', 'match (n:Person) where EXISTS(n.age) AND n.age >40 return n.name ');` function instead, 
the performances are comparable, even if the query without the `return custom.return40()` is cached better, given that is in pure Cypher, and therefore by executing the query several times it becomes a little faster.

In any case, the issue is on 4.2.x.x. With 4.4.x.x the performance differences are slightly smaller.

I'm closing this issue, also considering that 4.2.x.x. is no longer supported by APOC.
Feel free to reopen it if you feel it is necessary.

**Closed by vga91** 2023-11-21 14:04 UTC
Labels: extended-functionality
