### ISSUE TITLE
apoc.load.directory() fails on Windows

### ISSUE THREAD

**Issue by odessit55** [neo4j-contrib/neo4j-apoc-procedures#2334] opened 2021-11-17 18:43 UTC
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discu
<img width="808" alt="apoc_load_dir_issue" src="https://user-images.githubusercontent.com/9523547/142262475-45b3afa5-1fdc-4c4c-a38b-12ff022afe46.PNG">
ssion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)
list files

## Actual Behavior (Mandatory)
errors out

## How to Reproduce the Problem
in screen shot
### Simple Dataset (where it's possibile)

```
//Insert here a set of Cypher statements that helps us to reproduce the problem

```

### Steps (Mandatory)

  1.in screenshot
  1.
  1.

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS:
  - Neo4j:
  - Neo4j-Apoc:

**Comment by kavaliro** [comment] 2021-11-22 20:03
I also see this error, using
`CALL apoc.load.directory('*.csv','.')`
Additionally,
`CALL apoc.load.csv($datafile,{limit:25}) YIELD map`
fails when
`LOAD CSV WITH HEADERS FROM $datafile AS row WITH row RETURN row LIMIT 25`
works. I suspect it is related.

**Comment by vga91** [comment] 2022-10-05 15:04
@odessit55 @kavaliro 
This bug should have been fixed by https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/2490, feel free to reopen the issue if the problem is still present.

**Closed by vga91** 2022-10-05 15:04 UTC
