### ISSUE TITLE
APOC doesn't play nicely with GraphAware extensions (server 3.3.0)

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-apoc-procedures#656] opened 2017-11-12 00:47 UTC
When mixing APOC together with GraphAware NLP extensions, the server (3.3.0) fails to start.  The server will start either with APOC alone, or with the 3 GraphAware involved JARs below alone, but not with both.   After some experimentation, it doesn't appear to be possible to have both in the same server.

Versions:
```
[plugins]$ ls
apoc-3.2.3.5-all.jar				graphaware-server-enterprise-all-3.3.0.51.jar
graphaware-nlp-3.3.0.51.1.jar			nlp-opennlp-3.3.0.51.1.jar
```

Root cause appears to be `java.lang.NoClassDefFoundError: org/neo4j/kernel/impl/util/JobScheduler`

Relevant `neo4j.conf` snippets:
```
dbms.security.procedures.unrestricted=apoc.*,ga.*
dbms.security.procedures.whitelist=apoc.log.*,apoc.coll.*,apoc.convert.*,apoc.load.*,apoc.algo.*,apoc.text.*,ga.nlp.*

dbms.unmanaged_extension_classes=com.graphaware.server=/graphaware
com.graphaware.runtime.enabled=true
com.graphaware.module.NLP.1=com.graphaware.nlp.module.NLPBootstrapper
```

Error log:
```
2017-11-12 00:43:57.133+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@1bae316d' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.impl.util.JobScheduler". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@1bae316d' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.impl.util.JobScheduler".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@1bae316d' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.impl.util.JobScheduler".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:218)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@1bae316d' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.impl.util.JobScheduler".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:210)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /var/lib/neo4j/data/databases/graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:211)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:126)
	at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:58)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.KernelExtensions@4816278d' failed to initialize. Please see the attached cause exception "org.neo4j.kernel.impl.util.JobScheduler".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:427)
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:62)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:98)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:207)
	... 9 more
Caused by: java.lang.NoClassDefFoundError: org/neo4j/kernel/impl/util/JobScheduler
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at sun.misc.ProxyGenerator.generateClassFile(ProxyGenerator.java:451)
	at sun.misc.ProxyGenerator.generateProxyClass(ProxyGenerator.java:339)
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:639)
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)
	at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
	at java.lang.reflect.WeakCache.get(WeakCache.java:127)
	at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719)
	at org.neo4j.kernel.impl.util.DependenciesProxy.dependencies(DependenciesProxy.java:55)
	at org.neo4j.kernel.extension.KernelExtensions.getKernelExtensionDependencies(KernelExtensions.java:125)
	at org.neo4j.kernel.extension.KernelExtensions.init(KernelExtensions.java:58)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:406)
	... 12 more
Caused by: java.lang.ClassNotFoundException: org.neo4j.kernel.impl.util.JobScheduler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 28 more
2017-11-12 00:43:57.135+0000 INFO  Neo4j Server shutdown initiated by request
```

**Comment by moxious** [comment] 2017-11-12 00:49
Paging @ikwattro as I'm not 100% sure whether this is actually an APOC issue or a GraphAware NLP issue.

**Comment by ikwattro** [comment] 2017-11-12 01:22
@moxious Yes we realized this today as well, this happens only on community, NLP is irrelevant here, the graphaware-framework and apoc together are the cause, we are investigating

**Comment by jexp** [comment] 2017-12-12 01:10
@ikwattro any findings?

**Comment by ikwattro** [comment] 2017-12-12 07:58
Nope :(

We checked all common dependencies between apoc and the GA framework, seems like in community class loading do not behave the same as in enterprise.

GA FW alone works well with community, it is only when combined with apoc that the issue arise.

**Comment by ikwattro** [comment] 2017-12-12 19:43
Fixed by https://github.com/graphaware/neo4j-framework/pull/85

**Comment by jexp** [comment] 2017-12-13 12:50
Thanks so much !!

**Comment by jexp** [comment] 2017-12-13 12:50
@moxious could you confirm?

**Comment by moxious** [comment] 2017-12-13 13:23
@jexp well, the issue is acknowledged on the graph-aware framework side.   I tried to verify the fix but failed, will put comments on the associated issue in that repo, which is here: https://github.com/graphaware/neo4j-framework/issues/83 -- but as there's nothing to be done on the APOC side, close this and #669 if you agree, pointing to that other issue.

**Closed** 2018-01-24 14:16 UTC
