### ISSUE TITLE
Neo4j High Memory usage potential leak?

### ISSUE THREAD

**Issue by USHPINDER** [neo4j-contrib/neo4j-apoc-procedures#3696] opened 2023-07-26 11:01 UTC
Why my neo4j memory going high when i am deleting nodes from neo4j  using below 

"CALL
 apoc.periodic.iterate(\"MATCH (cl:Node1 {id: '" + label1 + "'}) -[:BELONGS]-> (c) return c\",\"DETACH DELETE c\",
{ batchSize: " + deleteBatchSize + ", parallel: " + deleteParallelCheck + ", concurrency: " + deleteConcurrencySize + ", retries: " + deleteRetriesAttempts + " })"

Below are parameters for same

 delete.parallel.check=true
delete.batch.size=2000
delete.concurrency.size=20
delete.retries.attempts=3

**Comment by Lojjs** [comment] 2023-07-27 06:58
@USHPINDER Which version of Neo4j and APOC are you using?

**Comment by USHPINDER** [comment] 2023-07-28 11:46
@Lojjs 


name | version | edition
-- | -- | --
1 | "Neo4j Kernel" | "5.1.0" | "community"

Apoc:5.1.0

**Comment by Lojjs** [comment] 2023-07-31 06:47
Thanks. We will investigate and report back here.

**Comment by nadja-muller** [comment] 2023-07-31 09:45
A bit of a general reply before we look into this: The reason your memory is high may also be related to the batchSize and concurrency parameters you are using (which need to be optimized for the machine you run the query on). 
As an alternative, you could also use CALL IN TRANSACTIONS and see if the performance is better there. It doesn't support parallel execution, however.

**Comment by USHPINDER** [comment] 2023-08-02 06:15
@Lojjs Thanks. Will wait for your reply.

@nadja-muller for our scenario we have allocated around 30GB of memory and there are around 5 million nodes.

We need to use apoc plugin Issue is:

1.We insert---->Delete using APOC plugin---->reinsert and memory not come down...

**Comment by USHPINDER** [comment] 2023-08-08 07:24
@Lojjs  Can you help us here?

**Comment by nadja-muller** [comment] 2023-08-09 17:17
Hi. 
Apparently, passing on a reference between the inner transactions will cause all changes to be tracked in the outer transaction. The solution is to pass on the id of the node as opposed to the node reference itself.

Could you check if updating the query the following query solves your problem?
"CALL
apoc.periodic.iterate("MATCH (cl:Node1 {id: '" + label1 + "'}) -[:BELONGS]-> (c) return elementId(c) as id","MATCH (c) WHERE elementId(c) = id DETACH DELETE c",
{ batchSize: " + deleteBatchSize + ", parallel: " + deleteParallelCheck + ", concurrency: " + deleteConcurrencySize + ", retries: " + deleteRetriesAttempts + " })"

See also this article [here](https://neo4j.com/developer/kb/a-significant-change-in-apoc-periodic-iterate-in-apoc-4-0/)

**Comment by nadja-muller** [comment] 2023-08-23 15:53
I tried to repdocue this but the memory usage looks fine. Do you have a heap dump we could have a look at - or a more detailed description on how we can reproduce it?

**Comment by jexp** [comment] 2023-09-21 11:59
Let's just switch to default rebinding all that's passed in as parameters. I don't think people read the docs or the KB article.

**Comment by nadja-muller** [comment] 2023-09-28 09:02
Since haven't gotten any further feedback, I'm closing this issue. Feel free to reopen it if you would like further help.

**Closed by nadja-muller** 2023-09-28 09:02 UTC
Labels: core-functionality
