### ISSUE TITLE
Error: No jar URL found for version '4.2.5' in versions.json

### ISSUE THREAD

**Issue by cmaart** [neo4j-contrib/neo4j-apoc-procedures#2330] opened 2021-11-15 16:25 UTC
## Expected Behavior (Mandatory)
Using docker this fails for neo4j:4.2.5 image. That started happening today:
`docker run -e NEO4JLABS_PLUGINS='["""apoc""", """graph-data-science"""]' --name neo4j -it neo4j:4.2.5`

Seems like 4.2.5. is missing suddenly in https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json?

## Actual Behavior (Mandatory)
Throws error:

Fetching versions.json for Plugin 'apoc' from https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json
Error: No jar URL found for version '4.2.5' in versions.json from 'https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json'

## How to Reproduce the Problem
Using docker one can execute this:
`docker run -e NEO4JLABS_PLUGINS='["""apoc""", """graph-data-science"""]' --name neo4j -it neo4j:4.2.5`

Currently used versions

### Versions

  - OS: Windows 10
  - Neo4j: 4.2.5
  - Neo4j-Apoc:

**Comment by at0dd** [comment] 2021-11-15 17:03
Same for 4.2.3

**Comment by chasemc** [comment] 2021-11-15 17:39
Same (4.2.5), looks like the URLs are gone and it looks like the releases are too?

**Comment by jexp** [comment] 2021-11-15 19:56
sorry for that 

maven central made some changes to it's apis that we use to generate the file and we didn't notice that it was leaving off 90% of the results in the respones. 

Please try again, should be fixed now.

See https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json

**Comment by chasemc** [comment] 2021-11-17 14:34
Thanks @jexp

**Comment by chasemc** [comment] 2021-11-17 14:35
Confirmed v4.2.5 works

**Comment by jexp** [comment] 2021-11-17 15:33
Coolio

**Closed** 2021-11-17 15:33 UTC
