### ISSUE TITLE
Spatial doesn't play nicely with GraphAware Framrwork (server 3.3.0)

### ISSUE THREAD

**Issue by akshay2408** [neo4j-contrib/neo4j-apoc-procedures#669] opened 2017-11-20 12:48 UTC
When mixing SPATIAL together with GraphAware  framrwork, the server (3.3.0) fails to start. The server will start either with SPATIAL alone, or with the 3 GraphAware involved JARs below alone, but not with both. After some experimentation, it doesn't appear to be possible to have both in the same server.

Versions:

1. apoc-3.3.0.1-all.jar                           
2. graphaware-timetree-3.3.0.51.27.jar  
3. neo4j-spatial-0.25.2-neo4j-3.3.0-server-plugin.jar
4. graphaware-server-enterprise-all-3.3.0.51.jar  
5. graphaware-uuid-3.3.0.51.14.jar

Conf. file:

[conf.txt](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/1487666/conf.txt)

**Comment by moxious** [comment] 2017-12-11 21:00
Possible duplicate of #656

**Comment by jexp** [comment] 2018-01-24 14:17
should be fixed on the graphaware side.

**Closed by jexp** 2018-01-24 14:17 UTC
