### ISSUE TITLE
apoc.load.jsonParams does not work on neo4j 4.3.3

### ISSUE THREAD

**Issue by kuczera** [neo4j-contrib/neo4j-apoc-procedures#2219] opened 2021-09-23 14:58 UTC
When i try this query:

`WITH 'SELECT ?item ?itemLabel 
      WHERE{ ?item wdt:P31 wd:Q989255 . 
      SERVICE wikibase:label { bd:serviceParam wikibase:language 
      "[AUTO_LANGUAGE],en" } }' AS sparql 
// make a request to Wikidata
CALL apoc.load.jsonParams('http://query.wikidata.org/sparql?query=' + 
                           apoc.text.urlencode(sparql), 
                         { Accept: "application/sparql-results+json"}, null) 
YIELD value 
// Unwind results to row 
UNWIND value['results']['bindings'] as row 
// Prepare data 
WITH row['itemLabel']['value'] as race, 
     row['item']['value'] as url, 
     split(row['item']['value'],'/')[-1] as id 
// Store to Neo4j 
CREATE (r:Race) SET r.race = race, 
                    r.url = url, 
                    r.id = id;
`
i get this error.

`Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.load.jsonParams`: Caused by: java.lang.RuntimeException: Can't read url or key http://query.wikidata.org/sparql?query=SELECT+%253Fitem+%253FitemLabel+%250A++++++WHERE%257B+%253Fitem+wdt%253AP31+wd%253AQ989255+.+%250A++++++SERVICE+wikibase%253Alabel+%257B+bd%253AserviceParam+wikibase%253Alanguage+%250A++++++%2522%255BAUTO_LANGUAGE%255D%252Cen%2522+%257D+%257D as json: Server returned HTTP response code: 400 for URL: https://query.wikidata.org/sparql?query=SELECT+%253Fitem+%253FitemLabel+%250A++++++WHERE%257B+%253Fitem+wdt%253AP31+wd%253AQ989255+.+%250A++++++SERVICE+wikibase%253Alabel+%257B+bd%253AserviceParam+wikibase%253Alanguage+%250A++++++%2522%255BAUTO_LANGUAGE%255D%252Cen%2522+%257D+%257D`

On 3.5.29 it works.

**Comment by vga91** [comment] 2021-09-28 14:04
@kuczera 
With newer apoc versions, the load procedures already have a url encode under the hood.
Effectively it is not clear from the documentation, we should add this note.

However, you don't have to call the `apoc.text.urlencode`, otherwise double encoding is done. 
Can you try without the `urlencode` function?

**Comment by kuczera** [comment] 2021-09-28 18:45
Sorry, does not work:
`WITH 'SELECT ?item ?itemLabel 
      WHERE{ ?item wdt:P31 wd:Q989255 . 
      SERVICE wikibase:label { bd:serviceParam wikibase:language 
      "[AUTO_LANGUAGE],en" } }' AS sparql 
// make a request to Wikidata
CALL apoc.load.jsonParams('https://query.wikidata.org/sparql?query=' + sparql, { Accept: "application/sparql-results+json"}, null) 
YIELD value 
// Unwind results to row 
UNWIND value['results']['bindings'] as row 
// Prepare data 
WITH row['itemLabel']['value'] as race, 
     row['item']['value'] as url, 
     split(row['item']['value'],'/')[-1] as id 
// Store to Neo4j 
CREATE (r:Race) SET r.race = race, 
                    r.url = url, 
                    r.id = id;`

results:

`Failed to invoke procedure `apoc.load.jsonParams`: Caused by: java.net.URISyntaxException: Illegal character in query at index 46: https://query.wikidata.org/sparql?query=SELECT ?item ?itemLabel 
      WHERE{ ?item wdt:P31 wd:Q989255 . 
      SERVICE wikibase:label { bd:serviceParam wikibase:language 
      "[AUTO_LANGUAGE],en" } }`

**Comment by vga91** [comment] 2021-09-29 07:26
@kuczera 
Maybe you're using a not updated version?
Can you check your apoc version?
Just execute `RETURN apoc.version()` and check that is `4.3.0.2`, otherwise can you try with this one?

**Comment by kuczera** [comment] 2021-09-29 09:10
Version is 4.3.0.2 as suggested. The error complains about an illegal character ?
Query:
`WITH 'SELECT ?item ?itemLabel
      WHERE{ ?item wdt:P39 wd:Q181765 .
      SERVICE wikibase:label { bd:serviceParam wikibase:language
      "[AUTO_LANGUAGE],en" } }' AS sparql
// make a request to Wikidata
CALL apoc.load.jsonParams('https://query.wikidata.org/sparql?query=' + sparql,
                         { Accept: "application/sparql-results+json"}, null)
YIELD value
return value`

Errormessage:
`Neo.ClientError.Procedure.ProcedureCallFailed
Failed to invoke procedure `apoc.load.jsonParams`: Caused by: java.net.URISyntaxException: Illegal character in path at index 73: https://query.wikidata.org/sparql%3Fquery=SELECT%20%3Fitem%20%3FitemLabel
%20%20%20%20%20%20WHERE%7B%20%3Fitem%20wdt:P39%20wd:Q181765%20.
%20%20%20%20%20%20SERVICE%20wikibase:label%20%7B%20bd:serviceParam%20wikibase:language
%20%20%20%20%20%20%22%5BAUTO_LANGUAGE%5D,en%22%20%7D%20%7D`

**Comment by kuczera** [comment] 2021-09-29 13:20
The Problem is the newline in sparql. This works:
`// 01 Ethnische Gruppen
// Prepare a SPARQL query 
WITH 'SELECT ?item ?itemLabel WHERE{ ?item wdt:P31 wd:Q989255 . SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" } }' AS sparql 
// make a request to Wikidata
CALL apoc.load.jsonParams('https://query.wikidata.org/sparql?query=' + sparql, 
                         { Accept: "application/sparql-results+json"}, null) 
YIELD value 
// Unwind results to row 
UNWIND value['results']['bindings'] as row 
// Prepare data 
WITH row['itemLabel']['value'] as race, 
     row['item']['value'] as url, 
     split(row['item']['value'],'/')[-1] as id 
// Store to Neo4j 
CREATE (r:Race) SET r.race = race, 
                    r.url = url, 
                    r.id = id;
`

**Comment by arthcras** [comment] 2022-08-25 23:14
also with the following code got an error:
import_races_query = """

// Prepare a SPARQL query 
WITH 'SELECT ?item ?itemLabel WHERE{ ?item wdt:P31 wd:Q989255 . SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }}' AS sparql 
// make a request to Wikidata
CALL apoc.load.jsonParams('https://query.wikidata.org/sparql?query=' + 
                           sparql, 
                         { Accept: "application/sparql-results+json"}, null) 
YIELD value 
// Unwind results to row 
UNWIND value['results']['bindings'] as row 
// Prepare data 
WITH row['itemLabel']['value'] as race, 
     row['item']['value'] as url, 
     split(row['item']['value'],'/')[-1] as id 
// Store to Neo4j 
CREATE (r:Race) SET r.race = race, 
                    r.url = url, 
                    r.id = id

"""

r = run_query(import_races_query)
---------------------------------------------------------------------------
ClientError                               Traceback (most recent call last)
[<ipython-input-8-715d98a49cdc>](https://localhost:8080/#) in <module>
     21 """
     22 
---> 23 r = run_query(import_races_query)

6 frames
[/usr/local/lib/python3.7/dist-packages/neo4j/io/_common.py](https://localhost:8080/#) in on_failure(self, metadata)
    244         if callable(handler):
    245             handler()
--> 246         raise Neo4jError.hydrate(**metadata)
    247 
    248     def on_ignored(self, metadata=None):

ClientError: Failed to invoke procedure `apoc.load.jsonParams`: Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://query.wikidata.org/sparql?query=SELECT ?item ?itemLabel WHERE{ ?item wdt:P31 wd:Q989255 . SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" }}

**Comment by arthcras** [comment] 2022-08-25 23:15
any suggestions now to correct are welcome

**Comment by vga91** [comment] 2022-08-26 14:02
@arthcras 
Recently we have decided to change the url handling, so that particular cases such as `"\n"` and white spaces can be handled by `apoc.text.urlencode`.

Can you try your query by changing `CALL apoc.load.jsonParams('https://query.wikidata.org/sparql?query=' +
sparql,` with `CALL apoc.load.jsonParams('https://query.wikidata.org/sparql?query=' +
apoc.text.urlencode(sparql),`?

In case it doesn't work, can you provide your own version of neo4j and apoc?

**Comment by kuczera** [comment] 2022-08-26 16:33
Your query does not work but my first query now works.

**Comment by kuczera** [comment] 2022-08-26 17:08
apoc.version()
4.4.0.1

**Comment by arthcras** [comment] 2022-08-27 00:09
Ok will do and let you know
By the way the code was working on my desktop but not on colabs and then with a connection to a neo4j sandbox

**Comment by arthcras** [comment] 2022-08-27 10:03
i did the replacement for apoc.load.jsonParams('https://query.wikidata.org/sparql?query=' + sparql, with CALL apoc.load.jsonParams('https://query.wikidata.org/sparql?query=' + apoc.text.urlencode(sparql),? and it worked! thanks a lot
rgds arthur

**Comment by vga91** [comment] 2022-10-06 09:54
> Can you try your query by changing `CALL apoc.load.jsonParams('https://query.wikidata.org/sparql?query=' + sparql,` with `CALL apoc.load.jsonParams('https://query.wikidata.org/sparql?query=' + apoc.text.urlencode(sparql),`?
> 
> In case it doesn't work, can you provide your neo4j and apoc version?

Closing this as the solution has been provided

**Closed by vga91** 2022-10-06 09:54 UTC
