### ISSUE TITLE
APOC doesn't read config in 3.2.0 Community?

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#456] opened 2017-05-29 13:11 UTC

**Comment by InverseFalcon** [comment] 2017-06-02 19:54
The zipped/tar version seems to work, this likely affects just the executable versions, same as earlier versions. As I recall this was never fixed, we just gave guidance to add APOC to a couple different directories

**Comment by inserpio** [comment] 2017-06-05 12:11
We experimented the same problem with the windows installer during a training.
Need to look into it.

**Comment by AngeloBusato** [comment] 2017-09-01 14:04
@jexp the problem is in the windows installer when:
1)you run .exe file first of all
2)you put APOC jar into the two folders
3)you start neo.
In simple terms if you run the .exe before putting the apoc jar into the two folders.

But if you kill the neo4j process (in windows remains active after stopping the db and closing the .exe), and reopen the.exe and restart the db, it works.

So it is a windows problem with the installer.

if you put the jar into the two folders first of all, apoc reads config file. and the problem doesn't occur.

**Closed** 2021-05-12 13:59 UTC
Labels: Larus
