### ISSUE TITLE
apoc.refactor.rename.label assertion failure

### ISSUE THREAD

**Issue by shahargolan** [neo4j-contrib/neo4j-apoc-procedures#764] opened 2018-03-15 09:39 UTC
Using apoc 3.3.0.1 on neo 3.2.1 (browser):

`create (a:A:B)
`
```
match (a:A)
call apoc.refactor.rename.label("B", "BB", [a]) yield errorMessage
return *
```
Gives the cryptic error:

> Failed to invoke procedure `apoc.refactor.rename.label`: Caused by: java.lang.AssertionError: assertion failed

**Comment by sarmbruster** [comment] 2018-03-26 07:30
The root cause for this is a regression wrt `UNWIND` - which is called inside `apoc.refactor.rename.label`. This has been fixed already, see https://github.com/neo4j/neo4j/pull/11352. That fix should be part of Neo4j 3.3.5.

Closing off this issue since fix has been provided in Neo4j.

**Closed by sarmbruster** 2018-03-26 07:30 UTC
